version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: codemaker
    versions:
    - ">= 0"
  - dependency-name: "@jsii/*"
    versions:
    - ">= 0"
  - dependency-name: jsii*
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11.0.0-0"
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.4
    - 0.11.5
    - 0.11.6
    - 0.11.7
    - 0.11.8
    - 0.11.9
    - 0.8.36
    - 0.8.37
    - 0.8.38
    - 0.8.39
    - 0.8.40
    - 0.8.41
    - 0.8.42
    - 0.8.43
    - 0.8.44
    - 0.8.45
    - 0.8.46
    - 0.8.47
    - 0.8.48
    - 0.8.49
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.56
    - 0.8.57
    - 0.9.0
    - 0.9.1
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@types/table"
    versions:
    - 6.0.0
